### ISSUE TITLE
syntax error near unexpected token, Line 61

### ISSUE THREAD

**Issue by fishtenors** [MelonSmasher/chef_dynamic_motd#1]
Here is the full error output:

_-bash: /etc/profile.d/dymotd.sh: line 61: syntax error near unexpected token `$'do\r''
'bash: /etc/profile.d/dymotd.sh: line 61: `    do_

Machine is CentOS Linux release 7.3.1611 (Core)

**Comment by MelonSmasher** [comment]
Strange I have it running on CentOS and RHEL machines without any problems. That seems to be related to line Windows carriage-returns. The odd this is I saved that script on OSX. I'll see if [Dos2Unix](https://linux.die.net/man/1/dos2unix) cleans up the script.

**Comment by MelonSmasher** [comment]
Sorry this took me so long to get to. I missed this issue. I think* it should be good now.
